(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var g,aa="function"==typeof Object.create?Object.create:function(a){var b=function(){};b.prototype=a;return new b},ba=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");},n=ba(this),p;
if("function"==typeof Object.setPrototypeOf)p=Object.setPrototypeOf;else{var q;a:{var ca={ca:!0},r={};try{r.__proto__=ca;q=r.ca;break a}catch(a){}q=!1}p=q?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}
var t=p,v=function(a,b){a.prototype=aa(b.prototype);a.prototype.constructor=a;if(t)t(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c]},goog=goog||{},da=this||self,w=function(a,b){function c(){}c.prototype=b.prototype;a.prototype=new c;a.prototype.constructor=a};var x=function(a,b,c,d){a="translate3d("+a+"px, "+b+"px, "+c+"px)";d&&(a="rotate3d(0, 1, 0, "+d+"deg) "+a);return a},z=function(a,b,c){a=parseInt(a.getAttribute(b),10);isNaN(a)&&(a=c);return a};var A=["-ms-","-moz-","-webkit-",""],B=function(a,b,c,d){d=void 0===d?!1:d;for(var e,m,f=0;f<A.length;f++)e=A[f]+b,m=(d?A[f]:"")+c,a.style.setProperty(e,m)};var C=function(a,b){B(a,"transition","transform "+b+"ms",!0)};var D=function(a,b){return window.setTimeout(a,b)};var E=function(a,b,c){c=void 0===c?null:c;var d=document.createEvent("CustomEvent");d.initCustomEvent(a,!0,!0,c);b.dispatchEvent(d);return d},ea=function(a,b){b=void 0===b?null:b;var c=void 0===c?null:c;D(function(){var d=E("autoplayended",a,b);c&&c(d)},0)},fa=function(a,b){var c=function(d){a.removeEventListener("attached",c);b(d)};a.addEventListener("attached",c)},ha=function(a){var b=!1,c=null;return function(){b=!0;c||(b&&(a(),b=!1),c=D(function(){c=null;b&&(a(),b=!1)},250))}};var F=function(a,b){if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||!!(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a},G=function(a){return"gwd-page"==a.tagName.toLowerCase()||"gwd-page"==a.getAttribute("is")},ia=function(a){if(G(a))return a;for(;a&&9!=a.nodeType;)if((a=a.parentElement)&&G(a))return a;return null},H=function(a,b,c,d){d=(void 0===d?"":d)||b;a.hasAttribute(b)?(a=a.getAttribute(b),c.setAttribute(d,
a)):c.removeAttribute(d)},ja=function(a){return(a=a.hasAttribute("exit-urls")?a.getAttribute("exit-urls"):"")?a.split(",").map(function(b){return b.trim()}):[]};var ka=function(a){a=a.trim();return window.Enabler?window.Enabler.getUrl(a):a};var I=function(a){if(Error.captureStackTrace)Error.captureStackTrace(this,I);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))};w(I,Error);I.prototype.name="CustomError";var J=function(a,b){a=a.split("%s");for(var c="",d=a.length-1,e=0;e<d;e++)c+=a[e]+(e<b.length?b[e]:"%s");I.call(this,c+a[d])};w(J,I);J.prototype.name="AssertionError";var la=function(a,b,c){if(!a){var d="Assertion failed";if(b){d+=": "+b;var e=Array.prototype.slice.call(arguments,2)}throw new J(""+d,e||[]);}return a},ma=function(a,b){throw new J("Failure"+(a?": "+a:""),Array.prototype.slice.call(arguments,1));};var M=function(a,b){this.L=a===K&&b||"";this.ba=L};M.prototype.F=!0;M.prototype.C=function(){return this.L.toString()};M.prototype.toString=function(){return"SafeUrl{"+this.L+"}"};var na=function(a){if(a instanceof M&&a.constructor===M&&a.ba===L)return a.L;var b=typeof a;ma("expected object of type SafeUrl, got '"+a+"' of type "+("object"!=b?b:a?Array.isArray(a)?"array":b:"null"));return"type_error:SafeUrl"},oa=/^(?:(?:https?|mailto|ftp):|[^:/?#]*(?:[/?#]|$))/i,L={},K={};var N=function(){this.K=""};N.prototype.F=!0;N.prototype.C=function(){return this.K};N.prototype.toString=function(){return"SafeStyle{"+this.K+"}"};N.prototype.G=function(a){this.K=a};(new N).G("");var O=function(){this.J=""};O.prototype.F=!0;O.prototype.C=function(){return this.J};O.prototype.toString=function(){return"SafeStyleSheet{"+this.J+"}"};O.prototype.G=function(a){this.J=a};(new O).G("");var pa=function(a){var b=document.createElement("gwd-image");b.setAttribute("source",a);return b},P=function(a){var b=[];if(a){a=a.split(",");for(var c=0;c<a.length;c++)/^[\s\xa0]*$/.test(a[c])||b.push(pa(ka(a[c])))}return b},Q=function(a,b){for(var c=0;c<a.length;c++){var d=a[c];"gwd-image"==d.tagName.toLowerCase()&&(null!=b?d.setAttribute("scaling",b):d.removeAttribute("scaling"))}},R=function(a,b){return"left"==a||"backwards"==a?-b:b},S=function(a,b){return(a%b+b)%b};var qa=function(a){var b=a.currentIndex-1;return b-b%a.frameSnapInterval},T=function(a,b){this.h=a;this.j=null;this.oa=b;this.D=!1};
T.prototype.play=function(a,b,c){var d=this;b=void 0===b?"forwards":b;if(this.h.frameCount&&null==this.j){if(c){var e=Math.floor(a/c);a=c}else e=this.h.frameCount,a/=e;var m=[],f=qa(this.h);c=f;for(var h=0;h<e;h++){if(0<h||!this.oa)c=S(c+R(b,1),this.h.frameCount);m.push(c)}b=function(){if(m.length){var k=m.shift();d.D=!0;d.h.goToFrame(k+1);d.D=!1;E("frameautoplayed",d.h,{id:k+1})}else d.stop(!0),d.h.goToFrame(f+1)};this.j=window.setInterval(b,a);setTimeout(b)}};
T.prototype.stop=function(a){a=void 0===a?!1:a;!this.D&&this.j&&(window.clearInterval(this.j),ea(this.h,{completed:a}),this.j=null)};var ra=["pause-front-media","resume-next-media"],U=function(){var a=HTMLElement.call(this)||this;a.frames=[];a.a=null;a.b=0;a.s=1;a.m=new T(a,!0);a.V=!1;a.X=!1;return a};v(U,HTMLElement);g=U.prototype;g.attributeChangedCallback=function(a,b,c){switch(a){case "pause-front-media":this.V="true"==c;break;case "resume-next-media":this.X="true"==c}};g.gwdIsLoaded=function(){return!0};g.gwdLoad=function(){};g.goToFrame=function(a,b){this.stopRotation();0!=this.b&&(a>this.b?a=this.b:1>a&&(a=1),this.P(a,b))};
g.P=function(a){this.a=a-1};var V=function(a,b,c,d){if(null!=a.a){var e=a.s;e=S(a.a+R(b,void 0===e?1:e),a.s*Math.ceil(a.b/a.s));!d&&("forwards"==b&&e<a.a||"backwards"==b&&e>a.a)||a.goToFrame(e+1,c)}};g=U.prototype;g.goBackwards=function(a,b){V(this,"backwards",void 0===a?"slide":a,void 0===b?!0:b)};g.goForwards=function(a,b){V(this,"forwards",void 0===a?"slide":a,void 0===b?!0:b)};g.rotateOnce=function(a,b){this.m.play(void 0===a?0:a,b)};g.stopRotation=function(){this.m.stop()};
g.getFrame=function(a){if(0!=this.b)return this.frames[a-1]};var sa=function(a,b){if(null!=a.a&&a.a!=b){if(a.V)for(var c=Array.prototype.slice.call(a.frames[a.a].querySelectorAll("video, gwd-youtube, audio,gwd-video,gwd-audio")),d=0;d<c.length;d++){var e=c[d];e.pause&&e.pause()}if(a.X)for(a=Array.prototype.slice.call(a.frames[b].querySelectorAll("video, gwd-youtube, audio,gwd-video,gwd-audio")),b=0;b<a.length;b++)c=a[b],c.play&&c.play()}};
U.prototype.da=function(a){var b=a.length;a=a.splice(0,b);for(var c=0;c<b;c++){var d=a[c];"frameshown"==d?E(d,this,{id:this.currentIndex}):E(d,this)}};n.Object.defineProperties(U.prototype,{currentIndex:{configurable:!0,enumerable:!0,get:function(){return 0<this.b?this.a+1:void 0}},frameSnapInterval:{configurable:!0,enumerable:!0,get:function(){return this.s}},frameCount:{configurable:!0,enumerable:!0,get:function(){return this.b}}});
n.Object.defineProperties(U,{observedAttributes:{configurable:!0,enumerable:!0,get:function(){return ra}}});var ta="autoplay exit-urls transition-duration frame-width frame-height neighbor-rotation-y neighbor-translation-x neighbor-translation-y neighbor-translation-z start-frame show-reflection has-navigation navigation-highlight navigation-thumbnails images scaling pause-front-media resume-next-media".split(" "),W=function(){var a=U.call(this)||this;a.H=!1;a.g=null;a.R=-1;a.M=0;a.i=null;a.aa=a.ma.bind(a);a.$=a.na.bind(a);a.Z=a.la.bind(a);a.Y=a.ka.bind(a);a.B=E.bind(null,"firstinteraction",a);a.U=a.ia.bind(a);
a.W=ha(a.ja.bind(a));a.N=!1;a.I=[];a.l=a.da.bind(a,a.I);a.A=[];a.O=0;a.u=!1;a.c=null;a.o=0;a.m=new T(a,!1);a.f=null;a.S=!1;a.v=!1;return a};v(W,U);g=W.prototype;
g.connectedCallback=function(){if(!this.v){if(this.u=this.hasAttribute("images"))for(;this.firstChild;)this.removeChild(this.firstChild);var a=document.createElement("gwd-gesture");a.className="gesture";this.i=a;this.v=!0}a=this.i;this.o=this.o||this.clientWidth/2;a.addEventListener("trackstart",this.aa,!1);a.addEventListener("track",this.$,!1);a.addEventListener("trackend",this.Z,!1);a.addEventListener("tap",this.Y,!1);this.addEventListener("transitionend",this.l,!1);this.addEventListener("webkitTransitionEnd",
this.l,!1);this.gwdIsLoaded()||((a=ia(this))?a.gwdIsLoaded()&&this.gwdLoad():this.gwdLoad());this.S&&X(this);window.addEventListener("resize",this.W,!1)};
g.disconnectedCallback=function(){window.removeEventListener("resize",this.W,!1);var a=this.i;a.removeEventListener("trackstart",this.aa,!1);a.removeEventListener("track",this.$,!1);a.removeEventListener("trackend",this.Z,!1);a.removeEventListener("tap",this.Y,!1);this.removeEventListener("transitionend",this.l);this.removeEventListener("webkitTransitionEnd",this.l)};
g.attributeChangedCallback=function(a,b,c,d){switch(a){case "images":this.u=!0;this.b=0;this.a=null;this.frames=P(c||"");X(this);break;case "has-navigation":case "navigation-highlight":case "navigation-thumbnails":this.v&&ua(this);break;case "scaling":Q(this.frames,c);break;case "pause-front-media":case "resume-next-media":U.prototype.attributeChangedCallback.call(this,a,b,c,d);break;default:va(this)}};
g.P=function(a,b){b="none"!=b;var c=this.c.transitionDuration;sa(this,a-1);Y(this,b?c:0);Z(this,a-1)};g.rotateOnce=function(a,b){this.m.play((void 0===a?0:a)||this.c.transitionDuration*this.b,b)};g.gwdIsLoaded=function(){return this.H};g.gwdLoad=function(){if(!this.H&&!this.g){if(this.u)var a=P(this.getAttribute("images"));else{a=this.childNodes;for(var b=[],c=0,d=a.length;c<d;c++){var e=a[c];e.nodeType==Node.ELEMENT_NODE&&b.push(e)}a=b}this.frames=a;X(this)}};
var X=function(a){if(a.v){for(;a.firstChild;)a.removeChild(a.firstChild);a.f=null;a.g&&a.g.removeEventListener("pageload",a.U,!1);for(var b=a.frames,c=document.createElement("gwd-page"),d=0;d<b.length;d++){var e=b[d];B(e,"user-select","none");e.classList.add("frame");c.appendChild(e)}fa(c,c.gwdLoad.bind(c));a.g=c;c.className=a.hasAttribute("show-reflection")?"container reflection":"container";c.addEventListener("pageload",a.U,!1);Q(a.frames,a.getAttribute("scaling"));a.appendChild(c);a.appendChild(a.i)}else a.S=
!0};W.prototype.ia=function(a){this.g===a.target&&(this.H=!0,this.b=this.frames.length,this.A=[],this.O=this.b,wa(this),this.b&&this.c.autoplay&&D(this.rotateOnce.bind(this),0),ua(this),E("allframesloaded",this),E("ready",this))};var wa=function(a){xa(a);if(a.b){var b=a.c.pa-1;if(0>b||b>=a.b)b=0;Y(a,0);Z(a,b)}};W.prototype.ja=function(){this.o=this.clientWidth/2;wa(this)};
var xa=function(a){va(a);for(var b=0,c,d=0;d<a.frames.length;d++)c=a.frames[d],c.style.left=b+"px",c.style.width=a.c.frameWidth+"px",c.style.height=a.c.frameHeight+"px",b+=a.c.frameWidth},va=function(a){var b=a.frames;var c=z(a,"frame-width",Math.floor(.8*a.clientWidth));var d=a.hasAttribute("show-reflection"),e=z(a,"frame-height",d?Math.floor(4*a.clientHeight/7):Math.floor(6*a.clientHeight/7)),m=z(a,"neighbor-translation-x",Math.floor(c/8));if(a.hasAttribute("neighbor-translation-x")){a:{var f=c,
h=!0;if(a.hasAttribute("clamp-frame-size-to-image")){var k=a.getAttribute("clamp-frame-size-to-image");"true"==k?h=!0:"false"==k&&(h=!1)}if(h)if(k=a.hasAttribute("scaling")?a.getAttribute("scaling"):"contain",(h="contain"==k)||"none"==k)if(0==f||0==e)b=f;else{k=-1;c=b.length;for(var y=0;y<c;y++){var l=b[y];if("img"!=l.tagName.toLowerCase()&&"gwd-image"!=l.tagName.toLowerCase()){b=f;break a}var u=l.assetWidth?l.assetWidth:l.naturalWidth;l=l.assetHeight?l.assetHeight:l.naturalHeight;0<u&&0<l&&(k=Math.max(k,
h?u/l<f/e?u/l*e:f:u))}b=-1!=k?Math.min(f,k):f}else b=f;else b=f}c=b}b=z(a,"neighbor-translation-y",-Math.floor(e/10));f=z(a,"neighbor-translation-z",-e);h=z(a,"neighbor-rotation-y",38);k=z(a,"start-frame",2);u=e;a.f&&(u-=36);e=ja(a);y=a.hasAttribute("autoplay");l=parseInt(a.getAttribute("transition-duration"),10);isNaN(l)&&(l=600);a.c={autoplay:y,ea:e,frameWidth:c,frameHeight:u,fa:h,ga:m,T:b,ha:f,transitionDuration:l,qa:d,pa:k}};
W.prototype.ma=function(){null!=this.a&&(this.stopRotation(),this.M=this.a,Y(this,0))};W.prototype.na=function(a){if(this.b){this.B&&(this.B(),this.B=null);a=-a.dx/this.c.frameWidth;var b=Math.round(a);ya(this,this.M+b,a-b)}};W.prototype.la=function(){if(null!=this.a){Y(this,this.c.transitionDuration);var a=this.a;Z(this,a);this.M!=a&&(0==a?E("reachleftend",this):a==this.b-1&&E("reachrightend",this))}};
W.prototype.ka=function(a){if(this.b){var b=null;var c=this.i;var d=this.g,e=a.clientX,m=a.clientY,f=c.style["pointer-events"];c.style["pointer-events"]="none";e=d.ownerDocument.elementFromPoint(e,m);c.style["pointer-events"]=f;if(c=e&&F(d,e)?e:null){d=a.clientX;a=a.clientY;f=!1;"gwd-taparea"===c.tagName.toLowerCase()&&(f=c.ownerDocument.createEvent("Event"),f.initEvent("action",!0,!0),f.clientX=d,f.clientY=a,f=!c.dispatchEvent(f));if(f)return;for(a=0;a<this.b;a++)if(F(this.frames[a],c)){b=a;break}null!=
b&&(a=this.c.ea[b])&&!E("frameexit",this,{url:a}).detail.handled&&(a instanceof M||a instanceof M||(a="object"==typeof a&&a.F?a.C():String(a),la(oa.test(a),"%s does not match the safe URL pattern",a)||(a="about:invalid#zClosurez"),a=new M(K,a)),da.open(na(a),"",void 0,void 0))}null==b&&(b=null!=this.a?this.a:0);E("frametap",this,{element:this.frames[b],id:b+1})}};
var Y=function(a,b){a.N=0<b;a.g&&C(a.g,b);for(var c=0;c<a.b;c++)C(a.frames[c],b)},Z=function(a,b){a.frames[b]&&(a.a=b,ya(a,b,0,a.b),a.I.push("frameshown"),a.A[b]||(a.A[b]=!0,--a.O||a.I.push("allframesviewed")));a.N||a.l()},ya=function(a,b,c,d){d=void 0===d?1:d;for(var e=a.c,m,f,h=-d;h<=d;h++)if((m=a.frames[h+b])&&0<=c*h){0>h?f=1-Math.abs(c):0<h?f=Math.abs(c)-1:(sa(a,b),a.a=b,f=c);var k=Math.abs(f);m.style.setProperty("transform",x(e.ga*f,e.T*k,e.ha*k,e.fa*f))}a.R!=a.a&&null!=a.a&&(a.R=a.a,E("frameactivated",
a,{id:a.currentIndex}));a.g.style.setProperty("transform",x(a.o-(b+c+.5)*e.frameWidth,-e.T,0,void 0))},ua=function(a){var b=a.hasAttribute("has-navigation"),c=!!a.f;b&&!c?(b=a.id||a.getAttribute("data-gwd-grp-id"),a.f=document.createElement("gwd-gallerynavigation"),a.f.setAttribute("for",b),a.classList.add("has-navigation"),a.appendChild(a.f)):!b&&c&&(a.classList.remove("has-navigation"),a.removeChild(a.f),a.f=null);a.f&&(H(a,"navigation-highlight",a.f,"highlight"),H(a,"navigation-thumbnails",a.f,
"use-thumbnails"));xa(a)};n.Object.defineProperties(W,{observedAttributes:{configurable:!0,enumerable:!0,get:function(){return ta}}});customElements.define("gwd-carouselgallery",W);}).call(this);
